"use strict";
angular.module("audiometaDemo", ["audiometaWorker", "audiometa", "ngRoute"]).config(function($routeProvider) {
  return $routeProvider.when("/", {
    templateUrl: "views/main.html",
    controller: "MainCtrl"
  }).otherwise({
    redirectTo: "/"
  });
});

// ---
// generated by coffee-script 1.9.2