import DataSource, { Status } from "./SourceDetails.dto.js";

export const data = [
  //   "builderbook",
  //   "calculator",
  //   "coreui-free-react-admin-template",
  //   "Interview-questions-metadata",
  //   "jodit-react",
  //   "learn-react",
  //   "01-starting-project",
  // "blank-project",
  // "ChatApp",
  // "common-components",
  // "diff-app",
  // "dynamic-form-generation-proj",
  // "fa-search-react",
  // "GQL-Demo",
  // "graphql-full-course",
  // "interview-companies-info",
  // "learn-to-add-arrows-between-divs",
  // "my-http-example",
  // "my-library-testing-vite-ts-lib-imported-in-js-proj",
  // "my-resume-vite-app",
  // "react-draggable-example",
  // "react-express-mysql",
  // "react-fetch-rxjs-hook",
  // "react-markdown-blog",
  // "react-redux",
  // "react-redux-toolkit-tutorial",
  // "react-router-bootstrap-project",
  // "react-rtk-query-fetch-demo",
  // "react-rxjs-pagination-example",
  // "react-silver-price-chart",
  // "react-ts-basics",
  // "react-with-ts-ex1",
  // "redux-toolkit-example-crud",
  // "rest-service-consumer",
  // "resume-application",
  // "rxjs_react_chat",
  // "Section-03-01-starting-setup",
  // "section-06-01-starting-project",
  // "tasks-mgmt",
  // "TweetApp",
  // "next-gen-js-summary.pdf",
  // "Readme.md"
  //   "learn-react-and-next-ts",
  //   "next-ts-basics",
  // "spp-tweet-app-with-next-ts"
  //   "learn-to-create-react-library",
  // "react-js-library-test",
  // "react-js-library-with-vite",
  // "react-js-library-with-vite-playground",
  // "react-js-library-with-vite-receter-template",
  // "react-js-library-with-vite-receter-template-playground",
  // "react-storybook-v6",
  // "react-ts-library-test",
  // "react-ts-library-with-rollup",
  // "react-ts-library-with-rollup-playground",
  // "react-ts-library-with-vite",
  // "react-ts-library-with-vite-playground",
  // "Dev.To.ReactComponentLibraryPublication.md",
  // "React-story-book-tutorial.md",
  // "readme.md",
  // "storybook-version-history.md"
  //   "learn-to-create-utility-library",
  //   "ts-library-with-vite",
  //   "Readme.md",
  //   "learn-to-test-react-components",
  "CRA-react-unit-testing-ghulamabbas2",
  "jest-crashcourse-by-laith-academy",
  "jest-mock-vs-spy-mohokh67",
  "react-testing-tutorial-js-cra-silver-price-chart-with-codevolution",
  "react-testing-tutorial-ts-cra-with-codevolution",
  "react-testing-tutorial-ts-vite-with-codevolution",
  "react-unit-testing-library-with-vitest-and-ts",
  "tdd-in-react-router-with-ts-shoaibbhimani",
  "testing-express-server-with-jest",
  "testing-javascript-web-dev-simplified-with-jest",
  "unit-testing-library-with-vitest-and-js",
  "unit-testing-with-ts-and-jest-ghulamabbas2",
  "Common-Error-Warnings-And-Troubleshooting.md",
  "jest-companion-and-alternatives.md",
  "Readme.md",
  //   "learn-to-use-material-ui",
  //   "node-service-frontend",
  //   "problem-mgmt-nosql-frontend",
  //   "react-complete-guide",
  //   "react-draft-wysiwyg-test",
  //   "react-inner-scroll",
  //   "react-list-component",
  //   "react-playground",
  //   "recursive-react-tree",
  //   "Tree-Data-raversal-In-TS",
  //   "typecript-play",
  //   "typescript-compiler-play",
  //   "typescript-edwin-diaz-1",
  //   "webpack-and-typescript-coding-ninza-lesson-6",
  //   "webpak-typescript-coding-ninza",
  //   "documentation.md",
  //   "key-terminologies.md",
  //   "React-Optimization-Tips.md",
  //   "Readme.md",
  //   "references.md",
  //   "version-details.md",
]
  .map(
    (d) =>
      `
DataSource.fromObject({
    sourceName: "${d}",
    status: Status.NOT_IN_USE,
    sourceType: "Project",
    location: \`https://github.com/sameer05515/react-projects/learn-to-test-react-components/${d}\`,
    repositoryOrDbName: "repo",
    lastModified: "27/Jan/2025",
    owner: defaultOwnerName,
    purpose: \`
    TBD    
    \`,
    criticality: "Medium",
    notes: "Archived repository",
  })
  `
  )
  .join(",\n\n\n");

document.getElementById("my-pre-section").innerText = data;
